---
title: "Assignment_2 Milan M Shetty"
output:
  pdf_document: default
  html_document: default
date: "2023-09-3"
editor_options:
  chunk_output_type: console
---

```{r}
checkEvent = function(stops)
{
  # Initialize the current bus occupancy
  current_occupancy = 0
  
  for (stop in 1:stops) 
  {
    if (current_occupancy > 0) 
    {
      # Simulate passengers getting off the bus
      current_occupancy = current_occupancy - sum(sample(c(0, 1), current_occupancy,
          replace = TRUE, prob = c(0.8, 0.2)))
    }
    
    # Simulate new passengers getting on board
    current_occupancy = current_occupancy + sample(0:2, size = 1, prob = c(0.5, 0.4, 0.1)) 
  }
  
  # Return the final bus occupancy after all stops
  return(current_occupancy) 
}


```

```{r}
# Number of simulations
nsimulations = 10000

# Number of stops
stops = 10

# Initialize a variable for bus occupancy
current_occupancy = 0

# Simulate bus occupancy for multiple simulations
results = replicate(nsimulations, checkEvent(stops))

# Calculate the probability that the bus is empty
empty_bus_probability = mean(results == 0)

# Print the probability
empty_bus_probability

```

